DROP FUNCTION EXPCOND.CARGAR_SQL_LISTA;

CREATE OR REPLACE FUNCTION EXPCOND.CARGAR_SQL_LISTA (vFIRMA VARCHAR2, vSQL_LISTA TELEBANCA.tARREGLO_VARCHAR) RETURN VARCHAR2
IS
    vCAD_DESENC VARCHAR2(32767);
    vCAD_ENC VARCHAR2(32767);
    vRES JSON := JSON();
    vRES_DESENC PLS_INTEGER := 1;
    vFIRMA_ENC VARCHAR2(32767);
    vPOS_LLAVE_ENC VARCHAR2(32767);
    vPOS_LLAVE_DESENC VARCHAR2(32767);
BEGIN
    vFIRMA_ENC := SUBSTR(vFIRMA, 1, INSTR(vFIRMA, '.') - 1);
    
    IF ENC_DEC.VALIDATE_SIGNATURE(vFIRMA_ENC) = 1 THEN
        vPOS_LLAVE_ENC := SUBSTR(vFIRMA, INSTR(vFIRMA, '.') + 1);
        vPOS_LLAVE_DESENC := ENC_DEC.DECRYPT(vPOS_LLAVE_ENC);
        TRACEAR('0 - LLAVE OK', TRUE);
        FOR I IN 1 .. vSQL_LISTA.COUNT LOOP
            vCAD_ENC := vSQL_LISTA(I);
            vCAD_DESENC := ENC_DEC.DECRYPT_BY_KEY_INDEX(vCAD_ENC, vPOS_LLAVE_DESENC);
            IF vCAD_DESENC IS NOT NULL THEN
                TRACEAR(I || ' - ' || vCAD_DESENC);
                EXECUTE IMMEDIATE vCAD_DESENC;
            ELSE
                vCAD_DESENC := 'LA SENTENCIA ' || I || ' NO PUDO SER INTERPRETADA.';
                vRES_DESENC := 0;
                EXIT;
            END IF;
        END LOOP;
        
        IF vRES_DESENC = 1 THEN
            TELEBANCA.LEER_DATOS;
            TELEBANCA.PAGAR_MULTAS;
            vRES := TELEBANCA.DBF_ERRORES;
            vCAD_DESENC := vRES.TO_CHAR();
        END IF;
    ELSE
        vCAD_DESENC := '{ data : [], result : "FIRMA INCORRECTA." }';
    END IF;
    RETURN vCAD_DESENC;
EXCEPTION
    WHEN OTHERS THEN RETURN '{ data : [], result : "' || SQLERRM || '"}';
END CARGAR_SQL_LISTA;
/
